/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DatabaseOverview: typeof import('./src/components/database/DatabaseOverview.vue')['default']
    DatabaseUnlock: typeof import('./src/components/database/DatabaseUnlock.vue')['default']
    FieldInput: typeof import('./src/components/FieldInput.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TOTPField: typeof import('./src/components/TOTPField.vue')['default']
    WindowButtons: typeof import('./src/components/window/WindowButtons.vue')['default']
  }
}
