/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/database/': RouteRecordInfo<'/database/', '/database', Record<never, never>, Record<never, never>>,
    '/database/[i]/': RouteRecordInfo<'/database/[i]/', '/database/:i', { i: ParamValue<true> }, { i: ParamValue<false> }>,
    '/database/[i]/entry/[uuid]': RouteRecordInfo<'/database/[i]/entry/[uuid]', '/database/:i/entry/:uuid', { i: ParamValue<true>, uuid: ParamValue<true> }, { i: ParamValue<false>, uuid: ParamValue<false> }>,
    '/ErrorNotFound': RouteRecordInfo<'/ErrorNotFound', '/ErrorNotFound', Record<never, never>, Record<never, never>>,
  }
}
